# Generated by Django 6.0.3 on 2026-03-31 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('Msc', 'Msc'), ('Bsc', 'Bsc'), ('BBA', 'BBA')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('marks_obtained', models.IntegerField()),
                ('total_marks', models.IntegerField(default=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
