# Generated by Django 5.2.8 on 2026-04-07 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_course_alter_student_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField(choices=[(1, 'Hour 1'), (2, 'Hour 2'), (3, 'Hour 3'), (4, 'Hour 4'), (5, 'Hour 5'), (6, 'Hour 6')])),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Student.student')),
            ],
            options={
                'ordering': ['date', 'hour'],
                'unique_together': {('student', 'date', 'hour')},
            },
        ),
    ]
