# Generated by Django 5.2.8 on 2026-04-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
